spring.application.name: cloud-config-server
server.port: 9999
spring.cloud.config:
  label: master
  server:
    git:
      uri: https://github.com/cocokka/raft/cloud-config-repo
      searchPaths: /cloud-config-client